name: Dependency Management

on:
  schedule:
    # Run every Monday at 9:00 UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:
  push:
    paths:
      - 'package.json'
      - 'package-lock.json'
      - 'requirements.txt'
      - 'pyproject.toml'
      - 'poetry.lock'

jobs:
  check-dependencies:
    name: Check for Dependency Updates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
        if: hashFiles('**/package.json') != ''

      - name: Check npm outdated packages
        if: hashFiles('**/package.json') != ''
        continue-on-error: true
        run: |
          if [ -f "package.json" ]; then
            echo "## ðŸ“¦ NPM Dependencies" >> $GITHUB_STEP_SUMMARY
            npm outdated || echo "All packages up to date"
          fi

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
        if: hashFiles('**/requirements.txt') != '' || hashFiles('**/pyproject.toml') != ''

      - name: Check Python outdated packages
        if: hashFiles('**/requirements.txt') != '' || hashFiles('**/pyproject.toml') != ''
        continue-on-error: true
        run: |
          python -m pip install --upgrade pip
          if [ -f "requirements.txt" ]; then
            pip install -r requirements.txt
            echo "## ðŸ Python Dependencies" >> $GITHUB_STEP_SUMMARY
            pip list --outdated || echo "All packages up to date"
          fi

      - name: Create dependency report
        run: |
          cat >> $GITHUB_STEP_SUMMARY <<EOF
          
          ## ðŸ“Š Dependency Status Report
          
          **Generated:** $(date)
          **Branch:** ${GITHUB_REF_NAME}
          
          Review the output above to see which dependencies have updates available.
          
          ### Next Steps
          - Review major version updates carefully
          - Check changelogs for breaking changes
          - Test thoroughly before merging
          EOF

  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
        if: hashFiles('**/package.json') != ''

      - name: Run npm audit
        if: hashFiles('**/package.json') != ''
        continue-on-error: true
        run: |
          if [ -f "package.json" ]; then
            echo "## ðŸ”’ NPM Security Audit" >> $GITHUB_STEP_SUMMARY
            npm audit --json > npm-audit.json || true
            
            CRITICAL=$(jq '.metadata.vulnerabilities.critical // 0' npm-audit.json)
            HIGH=$(jq '.metadata.vulnerabilities.high // 0' npm-audit.json)
            MODERATE=$(jq '.metadata.vulnerabilities.moderate // 0' npm-audit.json)
            LOW=$(jq '.metadata.vulnerabilities.low // 0' npm-audit.json)
            
            echo "- ðŸ”´ Critical: $CRITICAL" >> $GITHUB_STEP_SUMMARY
            echo "- ðŸŸ  High: $HIGH" >> $GITHUB_STEP_SUMMARY
            echo "- ðŸŸ¡ Moderate: $MODERATE" >> $GITHUB_STEP_SUMMARY
            echo "- ðŸŸ¢ Low: $LOW" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            
            if [ "$CRITICAL" -gt 0 ] || [ "$HIGH" -gt 0 ]; then
              echo "âš ï¸  **Action Required:** Critical or high severity vulnerabilities found!" >> $GITHUB_STEP_SUMMARY
              echo "Run \`npm audit fix\` to automatically fix vulnerabilities." >> $GITHUB_STEP_SUMMARY
            fi
          fi

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
        if: hashFiles('**/requirements.txt') != '' || hashFiles('**/pyproject.toml') != ''

      - name: Run pip audit (safety)
        if: hashFiles('**/requirements.txt') != '' || hashFiles('**/pyproject.toml') != ''
        continue-on-error: true
        run: |
          python -m pip install --upgrade pip safety
          if [ -f "requirements.txt" ]; then
            echo "## ðŸ”’ Python Security Audit" >> $GITHUB_STEP_SUMMARY
            safety check --file requirements.txt --output json > safety-report.json || true
            
            if [ -f "safety-report.json" ]; then
              VULN_COUNT=$(jq '. | length' safety-report.json)
              echo "Found $VULN_COUNT vulnerabilities" >> $GITHUB_STEP_SUMMARY
              
              if [ "$VULN_COUNT" -gt 0 ]; then
                echo "âš ï¸  **Action Required:** Security vulnerabilities found in Python dependencies!" >> $GITHUB_STEP_SUMMARY
              fi
            fi
          fi

      - name: Upload security reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports-${{ github.sha }}
          path: |
            npm-audit.json
            safety-report.json
          retention-days: 30

  auto-update-dependencies:
    name: Auto-update Dependencies
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
        if: hashFiles('**/package.json') != ''

      - name: Update npm dependencies
        if: hashFiles('**/package.json') != ''
        run: |
          if [ -f "package.json" ]; then
            npm update
            npm audit fix || true
          fi

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
        if: hashFiles('**/requirements.txt') != '' || hashFiles('**/pyproject.toml') != ''

      - name: Update Python dependencies
        if: hashFiles('**/requirements.txt') != ''
        continue-on-error: true
        run: |
          python -m pip install --upgrade pip pip-tools
          if [ -f "requirements.txt" ]; then
            # Upgrade dependencies
            pip-compile --upgrade requirements.in -o requirements.txt 2>/dev/null || true
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update dependencies'
          title: 'ðŸ”„ Automated Dependency Updates'
          body: |
            ## ðŸ¤– Automated Dependency Update
            
            This PR contains automated dependency updates.
            
            ### Changes
            - Updated NPM packages to latest compatible versions
            - Updated Python packages to latest compatible versions
            - Applied security fixes where available
            
            ### Review Checklist
            - [ ] Review changelog for major version updates
            - [ ] Check for breaking changes
            - [ ] Verify all tests pass
            - [ ] Test locally before merging
            
            ### Generated by
            GitHub Actions on $(date)
          branch: chore/dependency-updates-${{ github.run_number }}
          delete-branch: true
          labels: |
            dependencies
            automated

  license-compliance:
    name: License Compliance Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
        if: hashFiles('**/package.json') != ''

      - name: Check npm licenses
        if: hashFiles('**/package.json') != ''
        continue-on-error: true
        run: |
          if [ -f "package.json" ]; then
            npm install -g license-checker
            npm install
            
            echo "## ðŸ“œ License Compliance Report" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "### NPM Dependencies" >> $GITHUB_STEP_SUMMARY
            license-checker --summary >> $GITHUB_STEP_SUMMARY || true
          fi

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
        if: hashFiles('**/requirements.txt') != '' || hashFiles('**/pyproject.toml') != ''

      - name: Check Python licenses
        if: hashFiles('**/requirements.txt') != ''
        continue-on-error: true
        run: |
          python -m pip install --upgrade pip pip-licenses
          if [ -f "requirements.txt" ]; then
            pip install -r requirements.txt
            
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "### Python Dependencies" >> $GITHUB_STEP_SUMMARY
            pip-licenses --format=markdown >> $GITHUB_STEP_SUMMARY || true
          fi

  dependency-graph:
    name: Generate Dependency Graph
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update dependency graph
        uses: githubactions/dependency-graph@v1
        continue-on-error: true
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
